/*
 * @author: zhao yongfei
 * @Date: 2023-06-18 14:22:42
 * @description: 
 * @LastEditTime: 2023-06-21 11:53:02
 * @LastEditors: zhao yongfei
 * @FilePath: /dfs-page-config/src/components.d.ts
 */
// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AgTable: typeof import('./components/agTable/AgTable.vue')['default']
    BasicInfo: typeof import('./components/rowComponents/basicInfo.vue')['default']
    ButtonGroup: typeof import('./components/ButtonGroup.vue')['default']
    Card: typeof import('./components/Card.vue')['default']
    CardText: typeof import('./components/rowComponents/cardText.vue')['default']
    CellItemEdit: typeof import('./components/CellItemEdit.vue')['default']
    CellOperation: typeof import('./components/CellOperation.vue')['default']
    ChildrenComponent: typeof import('./components/ChildrenComponent.vue')['default']
    Col: typeof import('./components/rowComponents/col.vue')['default']
    ColumnCheck: typeof import('./components/ColumnCheck.vue')['default']
    CommonDialog: typeof import('./components/CommonDialog.vue')['default']
    ComponentItem: typeof import('./components/ComponentItem.vue')['default']
    Descriptions: typeof import('./components/Descriptions.vue')['default']
    DetileFooter: typeof import('./components/rowComponents/detileFooter.vue')['default']
    DetileTag: typeof import('./components/rowComponents/detileTag.vue')['default']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    EleTable: typeof import('./components/eleTable/EleTable.vue')['default']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTimeSelect: typeof import('element-plus/es')['ElTimeSelect']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Form: typeof import('./components/form/Form.vue')['default']
    ImageList: typeof import('./components/rowComponents/imageList.vue')['default']
    ImageOne: typeof import('./components/rowComponents/imageOne.vue')['default']
    ImgCarousel: typeof import('./components/rowComponents/imgCarousel.vue')['default']
    LabelText: typeof import('./components/rowComponents/LabelText.vue')['default']
    Page: typeof import('./components/Page.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RowItem: typeof import('./components/rowItem.vue')['default']
    SearchTab: typeof import('./components/SearchTab.vue')['default']
    SplitScreen: typeof import('./components/SplitScreen.vue')['default']
    TagArr: typeof import('./components/rowComponents/tagArr.vue')['default']
    TextArr: typeof import('./components/rowComponents/textArr.vue')['default']
    Upload: typeof import('./components/Upload.vue')['default']
    UploadComp: typeof import('./components/uploadComp/UploadComp.vue')['default']
  }
}
